// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rag/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractAndStoreMemoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TextToAnalyze    string                 `protobuf:"bytes,3,opt,name=text_to_analyze,json=textToAnalyze,proto3" json:"text_to_analyze,omitempty"`
	ExistingMemories []*MemoryItem          `protobuf:"bytes,4,rep,name=existing_memories,json=existingMemories,proto3" json:"existing_memories,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtractAndStoreMemoryRequest) Reset() {
	*x = ExtractAndStoreMemoryRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractAndStoreMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractAndStoreMemoryRequest) ProtoMessage() {}

func (x *ExtractAndStoreMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractAndStoreMemoryRequest.ProtoReflect.Descriptor instead.
func (*ExtractAndStoreMemoryRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractAndStoreMemoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExtractAndStoreMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExtractAndStoreMemoryRequest) GetTextToAnalyze() string {
	if x != nil {
		return x.TextToAnalyze
	}
	return ""
}

func (x *ExtractAndStoreMemoryRequest) GetExistingMemories() []*MemoryItem {
	if x != nil {
		return x.ExistingMemories
	}
	return nil
}

type ExtractAndStoreMemoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MemoriesCreated int32                  `protobuf:"varint,2,opt,name=memories_created,json=memoriesCreated,proto3" json:"memories_created,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtractAndStoreMemoryResponse) Reset() {
	*x = ExtractAndStoreMemoryResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractAndStoreMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractAndStoreMemoryResponse) ProtoMessage() {}

func (x *ExtractAndStoreMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractAndStoreMemoryResponse.ProtoReflect.Descriptor instead.
func (*ExtractAndStoreMemoryResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractAndStoreMemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExtractAndStoreMemoryResponse) GetMemoriesCreated() int32 {
	if x != nil {
		return x.MemoriesCreated
	}
	return 0
}

type RetrieveContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QueryText     string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveContextRequest) Reset() {
	*x = RetrieveContextRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveContextRequest) ProtoMessage() {}

func (x *RetrieveContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveContextRequest.ProtoReflect.Descriptor instead.
func (*RetrieveContextRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetrieveContextRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *RetrieveContextRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MemoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemoryKind    string                 `protobuf:"bytes,2,opt,name=memory_kind,json=memoryKind,proto3" json:"memory_kind,omitempty"`
	MemoryScope   string                 `protobuf:"bytes,3,opt,name=memory_scope,json=memoryScope,proto3" json:"memory_scope,omitempty"`
	ContentText   string                 `protobuf:"bytes,4,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryItem) Reset() {
	*x = MemoryItem{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryItem) ProtoMessage() {}

func (x *MemoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryItem.ProtoReflect.Descriptor instead.
func (*MemoryItem) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryItem) GetMemoryKind() string {
	if x != nil {
		return x.MemoryKind
	}
	return ""
}

func (x *MemoryItem) GetMemoryScope() string {
	if x != nil {
		return x.MemoryScope
	}
	return ""
}

func (x *MemoryItem) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *MemoryItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RetrieveContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*MemoryItem          `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveContextResponse) Reset() {
	*x = RetrieveContextResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveContextResponse) ProtoMessage() {}

func (x *RetrieveContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveContextResponse.ProtoReflect.Descriptor instead.
func (*RetrieveContextResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveContextResponse) GetMemories() []*MemoryItem {
	if x != nil {
		return x.Memories
	}
	return nil
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\"\xbf\x01\n" +
	"\x1cExtractAndStoreMemoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12&\n" +
	"\x0ftext_to_analyze\x18\x03 \x01(\tR\rtextToAnalyze\x12?\n" +
	"\x11existing_memories\x18\x04 \x03(\v2\x12.rag.v1.MemoryItemR\x10existingMemories\"d\n" +
	"\x1dExtractAndStoreMemoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10memories_created\x18\x02 \x01(\x05R\x0fmemoriesCreated\"f\n" +
	"\x16RetrieveContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa2\x01\n" +
	"\n" +
	"MemoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmemory_kind\x18\x02 \x01(\tR\n" +
	"memoryKind\x12!\n" +
	"\fmemory_scope\x18\x03 \x01(\tR\vmemoryScope\x12!\n" +
	"\fcontent_text\x18\x04 \x01(\tR\vcontentText\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"I\n" +
	"\x17RetrieveContextResponse\x12.\n" +
	"\bmemories\x18\x01 \x03(\v2\x12.rag.v1.MemoryItemR\bmemories2\xca\x01\n" +
	"\n" +
	"RagService\x12f\n" +
	"\x15ExtractAndStoreMemory\x12$.rag.v1.ExtractAndStoreMemoryRequest\x1a%.rag.v1.ExtractAndStoreMemoryResponse\"\x00\x12T\n" +
	"\x0fRetrieveContext\x12\x1e.rag.v1.RetrieveContextRequest\x1a\x1f.rag.v1.RetrieveContextResponse\"\x00B1Z/github.com/xusk947/croki-proto/pkg/rag/v1;ragv1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rag_v1_rag_proto_goTypes = []any{
	(*ExtractAndStoreMemoryRequest)(nil),  // 0: rag.v1.ExtractAndStoreMemoryRequest
	(*ExtractAndStoreMemoryResponse)(nil), // 1: rag.v1.ExtractAndStoreMemoryResponse
	(*RetrieveContextRequest)(nil),        // 2: rag.v1.RetrieveContextRequest
	(*MemoryItem)(nil),                    // 3: rag.v1.MemoryItem
	(*RetrieveContextResponse)(nil),       // 4: rag.v1.RetrieveContextResponse
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	3, // 0: rag.v1.ExtractAndStoreMemoryRequest.existing_memories:type_name -> rag.v1.MemoryItem
	3, // 1: rag.v1.RetrieveContextResponse.memories:type_name -> rag.v1.MemoryItem
	0, // 2: rag.v1.RagService.ExtractAndStoreMemory:input_type -> rag.v1.ExtractAndStoreMemoryRequest
	2, // 3: rag.v1.RagService.RetrieveContext:input_type -> rag.v1.RetrieveContextRequest
	1, // 4: rag.v1.RagService.ExtractAndStoreMemory:output_type -> rag.v1.ExtractAndStoreMemoryResponse
	4, // 5: rag.v1.RagService.RetrieveContext:output_type -> rag.v1.RetrieveContextResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
