// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: agent/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespondRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelSessionKey string                 `protobuf:"bytes,2,opt,name=channel_session_key,json=channelSessionKey,proto3" json:"channel_session_key,omitempty"`
	Content           string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Model             string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	ClientRequestId   string                 `protobuf:"bytes,5,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	AttachmentFileId  string                 `protobuf:"bytes,6,opt,name=attachment_file_id,json=attachmentFileId,proto3" json:"attachment_file_id,omitempty"`
	AttachmentFileIds []string               `protobuf:"bytes,7,rep,name=attachment_file_ids,json=attachmentFileIds,proto3" json:"attachment_file_ids,omitempty"`
	Metadata          *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RespondRequest) Reset() {
	*x = RespondRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondRequest) ProtoMessage() {}

func (x *RespondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondRequest.ProtoReflect.Descriptor instead.
func (*RespondRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RespondRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RespondRequest) GetChannelSessionKey() string {
	if x != nil {
		return x.ChannelSessionKey
	}
	return ""
}

func (x *RespondRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RespondRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RespondRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *RespondRequest) GetAttachmentFileId() string {
	if x != nil {
		return x.AttachmentFileId
	}
	return ""
}

func (x *RespondRequest) GetAttachmentFileIds() []string {
	if x != nil {
		return x.AttachmentFileIds
	}
	return nil
}

func (x *RespondRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RespondResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Reply               *Message               `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	ReplyAttachmentUrls []string               `protobuf:"bytes,2,rep,name=reply_attachment_urls,json=replyAttachmentUrls,proto3" json:"reply_attachment_urls,omitempty"`
	Usage               *structpb.Struct       `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RespondResponse) Reset() {
	*x = RespondResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondResponse) ProtoMessage() {}

func (x *RespondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondResponse.ProtoReflect.Descriptor instead.
func (*RespondResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RespondResponse) GetReply() *Message {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *RespondResponse) GetReplyAttachmentUrls() []string {
	if x != nil {
		return x.ReplyAttachmentUrls
	}
	return nil
}

func (x *RespondResponse) GetUsage() *structpb.Struct {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentText   string                 `protobuf:"bytes,4,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xc8\x02\n" +
	"\x0eRespondRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x13channel_session_key\x18\x02 \x01(\tR\x11channelSessionKey\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12*\n" +
	"\x11client_request_id\x18\x05 \x01(\tR\x0fclientRequestId\x12,\n" +
	"\x12attachment_file_id\x18\x06 \x01(\tR\x10attachmentFileId\x12.\n" +
	"\x13attachment_file_ids\x18\a \x03(\tR\x11attachmentFileIds\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x9d\x01\n" +
	"\x0fRespondResponse\x12'\n" +
	"\x05reply\x18\x01 \x01(\v2\x11.agent.v1.MessageR\x05reply\x122\n" +
	"\x15reply_attachment_urls\x18\x02 \x03(\tR\x13replyAttachmentUrls\x12-\n" +
	"\x05usage\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05usage\"j\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fcontent_text\x18\x04 \x01(\tR\vcontentText2N\n" +
	"\fAgentService\x12>\n" +
	"\aRespond\x12\x18.agent.v1.RespondRequest\x1a\x19.agent.v1.RespondResponseB-Z+github.com/xusk947/croki-proto/pkg/agent/v1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agent_v1_agent_proto_goTypes = []any{
	(*RespondRequest)(nil),  // 0: agent.v1.RespondRequest
	(*RespondResponse)(nil), // 1: agent.v1.RespondResponse
	(*Message)(nil),         // 2: agent.v1.Message
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	3, // 0: agent.v1.RespondRequest.metadata:type_name -> google.protobuf.Struct
	2, // 1: agent.v1.RespondResponse.reply:type_name -> agent.v1.Message
	3, // 2: agent.v1.RespondResponse.usage:type_name -> google.protobuf.Struct
	0, // 3: agent.v1.AgentService.Respond:input_type -> agent.v1.RespondRequest
	1, // 4: agent.v1.AgentService.Respond:output_type -> agent.v1.RespondResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
