// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tools/v1/tools.proto

package toolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_tools_v1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{0}
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_tools_v1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{1}
}

func (x *ListToolsResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolDefinition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersSchemaJson string                 `protobuf:"bytes,3,opt,name=parameters_schema_json,json=parametersSchemaJson,proto3" json:"parameters_schema_json,omitempty"`
	Usage                string                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	Examples             []string               `protobuf:"bytes,5,rep,name=examples,proto3" json:"examples,omitempty"`
	Aliases              []string               `protobuf:"bytes,6,rep,name=aliases,proto3" json:"aliases,omitempty"`
	PrimaryParameter     string                 `protobuf:"bytes,7,opt,name=primary_parameter,json=primaryParameter,proto3" json:"primary_parameter,omitempty"`
	Parameters           []*Parameter           `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_tools_v1_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParametersSchemaJson() string {
	if x != nil {
		return x.ParametersSchemaJson
	}
	return ""
}

func (x *ToolDefinition) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *ToolDefinition) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *ToolDefinition) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ToolDefinition) GetPrimaryParameter() string {
	if x != nil {
		return x.PrimaryParameter
	}
	return ""
}

func (x *ToolDefinition) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Enum          []string               `protobuf:"bytes,4,rep,name=enum,proto3" json:"enum,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_tools_v1_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{3}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parameter) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	Context       *ExecutionContext      `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // current user message or related content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_tools_v1_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *ExecuteRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ExecutionContext struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Channel:
	//
	//	*ExecutionContext_Telegram
	//	*ExecutionContext_Web
	Channel       isExecutionContext_Channel `protobuf_oneof:"channel"`
	System        *SystemContext             `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_tools_v1_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecutionContext) GetChannel() isExecutionContext_Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ExecutionContext) GetTelegram() *TelegramContext {
	if x != nil {
		if x, ok := x.Channel.(*ExecutionContext_Telegram); ok {
			return x.Telegram
		}
	}
	return nil
}

func (x *ExecutionContext) GetWeb() *WebContext {
	if x != nil {
		if x, ok := x.Channel.(*ExecutionContext_Web); ok {
			return x.Web
		}
	}
	return nil
}

func (x *ExecutionContext) GetSystem() *SystemContext {
	if x != nil {
		return x.System
	}
	return nil
}

type isExecutionContext_Channel interface {
	isExecutionContext_Channel()
}

type ExecutionContext_Telegram struct {
	Telegram *TelegramContext `protobuf:"bytes,2,opt,name=telegram,proto3,oneof"`
}

type ExecutionContext_Web struct {
	Web *WebContext `protobuf:"bytes,3,opt,name=web,proto3,oneof"`
}

func (*ExecutionContext_Telegram) isExecutionContext_Channel() {}

func (*ExecutionContext_Web) isExecutionContext_Channel() {}

type TelegramContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramContext) Reset() {
	*x = TelegramContext{}
	mi := &file_tools_v1_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramContext) ProtoMessage() {}

func (x *TelegramContext) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramContext.ProtoReflect.Descriptor instead.
func (*TelegramContext) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{6}
}

func (x *TelegramContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TelegramContext) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TelegramContext) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type WebContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebContext) Reset() {
	*x = WebContext{}
	mi := &file_tools_v1_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebContext) ProtoMessage() {}

func (x *WebContext) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebContext.ProtoReflect.Descriptor instead.
func (*WebContext) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{7}
}

func (x *WebContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SystemContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemContext) Reset() {
	*x = SystemContext{}
	mi := &file_tools_v1_tools_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemContext) ProtoMessage() {}

func (x *SystemContext) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemContext.ProtoReflect.Descriptor instead.
func (*SystemContext) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{8}
}

func (x *SystemContext) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SystemContext) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *SystemContext) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    string                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"` // Tool result content as JSON (e.g. {"content": "...", "tool_name": "..."})
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // Error message if execution failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_tools_v1_tools_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tools_v1_tools_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_tools_v1_tools_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tools_v1_tools_proto protoreflect.FileDescriptor

const file_tools_v1_tools_proto_rawDesc = "" +
	"\n" +
	"\x14tools/v1/tools.proto\x12\btools.v1\"\x12\n" +
	"\x10ListToolsRequest\"C\n" +
	"\x11ListToolsResponse\x12.\n" +
	"\x05tools\x18\x01 \x03(\v2\x18.tools.v1.ToolDefinitionR\x05tools\"\xaa\x02\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\x16parameters_schema_json\x18\x03 \x01(\tR\x14parametersSchemaJson\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\tR\x05usage\x12\x1a\n" +
	"\bexamples\x18\x05 \x03(\tR\bexamples\x12\x18\n" +
	"\aaliases\x18\x06 \x03(\tR\aaliases\x12+\n" +
	"\x11primary_parameter\x18\a \x01(\tR\x10primaryParameter\x123\n" +
	"\n" +
	"parameters\x18\b \x03(\v2\x13.tools.v1.ParameterR\n" +
	"parameters\"\x85\x01\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04enum\x18\x04 \x03(\tR\x04enum\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\"\x9a\x01\n" +
	"\x0eExecuteRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\tR\bargsJson\x124\n" +
	"\acontext\x18\x03 \x01(\v2\x1a.tools.v1.ExecutionContextR\acontext\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\xd0\x01\n" +
	"\x10ExecutionContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x127\n" +
	"\btelegram\x18\x02 \x01(\v2\x19.tools.v1.TelegramContextH\x00R\btelegram\x12(\n" +
	"\x03web\x18\x03 \x01(\v2\x14.tools.v1.WebContextH\x00R\x03web\x12/\n" +
	"\x06system\x18\x04 \x01(\v2\x17.tools.v1.SystemContextR\x06systemB\t\n" +
	"\achannel\"b\n" +
	"\x0fTelegramContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\"%\n" +
	"\n" +
	"WebContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"[\n" +
	"\rSystemContext\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"H\n" +
	"\x0fExecuteResponse\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x93\x01\n" +
	"\vToolService\x12D\n" +
	"\tListTools\x12\x1a.tools.v1.ListToolsRequest\x1a\x1b.tools.v1.ListToolsResponse\x12>\n" +
	"\aExecute\x12\x18.tools.v1.ExecuteRequest\x1a\x19.tools.v1.ExecuteResponseB4Z2github.com/xusk947/croki-proto/pkg/toolsv1;toolsv1b\x06proto3"

var (
	file_tools_v1_tools_proto_rawDescOnce sync.Once
	file_tools_v1_tools_proto_rawDescData []byte
)

func file_tools_v1_tools_proto_rawDescGZIP() []byte {
	file_tools_v1_tools_proto_rawDescOnce.Do(func() {
		file_tools_v1_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tools_v1_tools_proto_rawDesc), len(file_tools_v1_tools_proto_rawDesc)))
	})
	return file_tools_v1_tools_proto_rawDescData
}

var file_tools_v1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tools_v1_tools_proto_goTypes = []any{
	(*ListToolsRequest)(nil),  // 0: tools.v1.ListToolsRequest
	(*ListToolsResponse)(nil), // 1: tools.v1.ListToolsResponse
	(*ToolDefinition)(nil),    // 2: tools.v1.ToolDefinition
	(*Parameter)(nil),         // 3: tools.v1.Parameter
	(*ExecuteRequest)(nil),    // 4: tools.v1.ExecuteRequest
	(*ExecutionContext)(nil),  // 5: tools.v1.ExecutionContext
	(*TelegramContext)(nil),   // 6: tools.v1.TelegramContext
	(*WebContext)(nil),        // 7: tools.v1.WebContext
	(*SystemContext)(nil),     // 8: tools.v1.SystemContext
	(*ExecuteResponse)(nil),   // 9: tools.v1.ExecuteResponse
}
var file_tools_v1_tools_proto_depIdxs = []int32{
	2, // 0: tools.v1.ListToolsResponse.tools:type_name -> tools.v1.ToolDefinition
	3, // 1: tools.v1.ToolDefinition.parameters:type_name -> tools.v1.Parameter
	5, // 2: tools.v1.ExecuteRequest.context:type_name -> tools.v1.ExecutionContext
	6, // 3: tools.v1.ExecutionContext.telegram:type_name -> tools.v1.TelegramContext
	7, // 4: tools.v1.ExecutionContext.web:type_name -> tools.v1.WebContext
	8, // 5: tools.v1.ExecutionContext.system:type_name -> tools.v1.SystemContext
	0, // 6: tools.v1.ToolService.ListTools:input_type -> tools.v1.ListToolsRequest
	4, // 7: tools.v1.ToolService.Execute:input_type -> tools.v1.ExecuteRequest
	1, // 8: tools.v1.ToolService.ListTools:output_type -> tools.v1.ListToolsResponse
	9, // 9: tools.v1.ToolService.Execute:output_type -> tools.v1.ExecuteResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tools_v1_tools_proto_init() }
func file_tools_v1_tools_proto_init() {
	if File_tools_v1_tools_proto != nil {
		return
	}
	file_tools_v1_tools_proto_msgTypes[5].OneofWrappers = []any{
		(*ExecutionContext_Telegram)(nil),
		(*ExecutionContext_Web)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tools_v1_tools_proto_rawDesc), len(file_tools_v1_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tools_v1_tools_proto_goTypes,
		DependencyIndexes: file_tools_v1_tools_proto_depIdxs,
		MessageInfos:      file_tools_v1_tools_proto_msgTypes,
	}.Build()
	File_tools_v1_tools_proto = out.File
	file_tools_v1_tools_proto_goTypes = nil
	file_tools_v1_tools_proto_depIdxs = nil
}
