// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginWithTelegramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitData      string                 `protobuf:"bytes,1,opt,name=init_data,json=initData,proto3" json:"init_data,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithTelegramRequest) Reset() {
	*x = LoginWithTelegramRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithTelegramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithTelegramRequest) ProtoMessage() {}

func (x *LoginWithTelegramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithTelegramRequest.ProtoReflect.Descriptor instead.
func (*LoginWithTelegramRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginWithTelegramRequest) GetInitData() string {
	if x != nil {
		return x.InitData
	}
	return ""
}

func (x *LoginWithTelegramRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginWithTelegramRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginWithGoogleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithGoogleRequest) Reset() {
	*x = LoginWithGoogleRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithGoogleRequest) ProtoMessage() {}

func (x *LoginWithGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithGoogleRequest.ProtoReflect.Descriptor instead.
func (*LoginWithGoogleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginWithGoogleRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *LoginWithGoogleRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginWithGoogleRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RefreshSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshSessionRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RefreshSessionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	User                  *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Account               *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Session               *Session               `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	AccessToken           string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt  string                 `protobuf:"bytes,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt string                 `protobuf:"bytes,7,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	TokenType             string                 `protobuf:"bytes,8,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Telegram              *Telegram              `protobuf:"bytes,9,opt,name=telegram,proto3" json:"telegram,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *LoginResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetAccessTokenExpiresAt() string {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshTokenExpiresAt() string {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return ""
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResponse) GetTelegram() *Telegram {
	if x != nil {
		return x.Telegram
	}
	return nil
}

type RefreshSessionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Session               *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	AccessToken           string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt  string                 `protobuf:"bytes,3,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt string                 `protobuf:"bytes,5,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	TokenType             string                 `protobuf:"bytes,6,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RefreshSessionResponse) Reset() {
	*x = RefreshSessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionResponse) ProtoMessage() {}

func (x *RefreshSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RefreshSessionResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshSessionResponse) GetAccessTokenExpiresAt() string {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return ""
}

func (x *RefreshSessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshSessionResponse) GetRefreshTokenExpiresAt() string {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return ""
}

func (x *RefreshSessionResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type GetJWKSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwksJson      []byte                 `protobuf:"bytes,1,opt,name=jwks_json,json=jwksJson,proto3" json:"jwks_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSResponse) Reset() {
	*x = GetJWKSResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSResponse) ProtoMessage() {}

func (x *GetJWKSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSResponse.ProtoReflect.Descriptor instead.
func (*GetJWKSResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetJWKSResponse) GetJwksJson() []byte {
	if x != nil {
		return x.JwksJson
	}
	return nil
}

type GetSessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequest) Reset() {
	*x = GetSessionStatusRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequest) ProtoMessage() {}

func (x *GetSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSessionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ClientType    string                 `protobuf:"bytes,5,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusResponse) Reset() {
	*x = GetSessionStatusResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusResponse) ProtoMessage() {}

func (x *GetSessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetSessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSessionStatusResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *GetSessionStatusResponse) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerifiedAt string                 `protobuf:"bytes,4,opt,name=email_verified_at,json=emailVerifiedAt,proto3" json:"email_verified_at,omitempty"`
	Image           string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetEmailVerifiedAt() string {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return ""
}

func (x *User) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Account) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Session) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Session) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Telegram struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId               string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TelegramUserId          int64                  `protobuf:"varint,3,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	Username                string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	FirstName               string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	LanguageCode            string                 `protobuf:"bytes,7,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	IsPremium               bool                   `protobuf:"varint,8,opt,name=is_premium,json=isPremium,proto3" json:"is_premium,omitempty"`
	AllowsWriteToPm         bool                   `protobuf:"varint,9,opt,name=allows_write_to_pm,json=allowsWriteToPm,proto3" json:"allows_write_to_pm,omitempty"`
	PhotoUrl                string                 `protobuf:"bytes,10,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	AuthDate                string                 `protobuf:"bytes,11,opt,name=auth_date,json=authDate,proto3" json:"auth_date,omitempty"`
	QueryId                 string                 `protobuf:"bytes,12,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	StartParam              string                 `protobuf:"bytes,13,opt,name=start_param,json=startParam,proto3" json:"start_param,omitempty"`
	CanSendAfter            int32                  `protobuf:"varint,14,opt,name=can_send_after,json=canSendAfter,proto3" json:"can_send_after,omitempty"`
	ChatId                  int64                  `protobuf:"varint,15,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatType                string                 `protobuf:"bytes,16,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	ChatTitle               string                 `protobuf:"bytes,17,opt,name=chat_title,json=chatTitle,proto3" json:"chat_title,omitempty"`
	ChatUsername            string                 `protobuf:"bytes,18,opt,name=chat_username,json=chatUsername,proto3" json:"chat_username,omitempty"`
	ChatPhotoUrl            string                 `protobuf:"bytes,19,opt,name=chat_photo_url,json=chatPhotoUrl,proto3" json:"chat_photo_url,omitempty"`
	ChatInstance            string                 `protobuf:"bytes,20,opt,name=chat_instance,json=chatInstance,proto3" json:"chat_instance,omitempty"`
	ReceiverId              int64                  `protobuf:"varint,21,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ReceiverUsername        string                 `protobuf:"bytes,22,opt,name=receiver_username,json=receiverUsername,proto3" json:"receiver_username,omitempty"`
	ReceiverFirstName       string                 `protobuf:"bytes,23,opt,name=receiver_first_name,json=receiverFirstName,proto3" json:"receiver_first_name,omitempty"`
	ReceiverLastName        string                 `protobuf:"bytes,24,opt,name=receiver_last_name,json=receiverLastName,proto3" json:"receiver_last_name,omitempty"`
	ReceiverLanguageCode    string                 `protobuf:"bytes,25,opt,name=receiver_language_code,json=receiverLanguageCode,proto3" json:"receiver_language_code,omitempty"`
	ReceiverIsPremium       bool                   `protobuf:"varint,26,opt,name=receiver_is_premium,json=receiverIsPremium,proto3" json:"receiver_is_premium,omitempty"`
	ReceiverAllowsWriteToPm bool                   `protobuf:"varint,27,opt,name=receiver_allows_write_to_pm,json=receiverAllowsWriteToPm,proto3" json:"receiver_allows_write_to_pm,omitempty"`
	ReceiverPhotoUrl        string                 `protobuf:"bytes,28,opt,name=receiver_photo_url,json=receiverPhotoUrl,proto3" json:"receiver_photo_url,omitempty"`
	Hash                    string                 `protobuf:"bytes,29,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature               string                 `protobuf:"bytes,30,opt,name=signature,proto3" json:"signature,omitempty"`
	RawInitData             string                 `protobuf:"bytes,31,opt,name=raw_init_data,json=rawInitData,proto3" json:"raw_init_data,omitempty"`
	CreatedAt               string                 `protobuf:"bytes,32,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               string                 `protobuf:"bytes,33,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Telegram) Reset() {
	*x = Telegram{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telegram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telegram) ProtoMessage() {}

func (x *Telegram) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telegram.ProtoReflect.Descriptor instead.
func (*Telegram) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *Telegram) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Telegram) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Telegram) GetTelegramUserId() int64 {
	if x != nil {
		return x.TelegramUserId
	}
	return 0
}

func (x *Telegram) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Telegram) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Telegram) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Telegram) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *Telegram) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *Telegram) GetAllowsWriteToPm() bool {
	if x != nil {
		return x.AllowsWriteToPm
	}
	return false
}

func (x *Telegram) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Telegram) GetAuthDate() string {
	if x != nil {
		return x.AuthDate
	}
	return ""
}

func (x *Telegram) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *Telegram) GetStartParam() string {
	if x != nil {
		return x.StartParam
	}
	return ""
}

func (x *Telegram) GetCanSendAfter() int32 {
	if x != nil {
		return x.CanSendAfter
	}
	return 0
}

func (x *Telegram) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Telegram) GetChatType() string {
	if x != nil {
		return x.ChatType
	}
	return ""
}

func (x *Telegram) GetChatTitle() string {
	if x != nil {
		return x.ChatTitle
	}
	return ""
}

func (x *Telegram) GetChatUsername() string {
	if x != nil {
		return x.ChatUsername
	}
	return ""
}

func (x *Telegram) GetChatPhotoUrl() string {
	if x != nil {
		return x.ChatPhotoUrl
	}
	return ""
}

func (x *Telegram) GetChatInstance() string {
	if x != nil {
		return x.ChatInstance
	}
	return ""
}

func (x *Telegram) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Telegram) GetReceiverUsername() string {
	if x != nil {
		return x.ReceiverUsername
	}
	return ""
}

func (x *Telegram) GetReceiverFirstName() string {
	if x != nil {
		return x.ReceiverFirstName
	}
	return ""
}

func (x *Telegram) GetReceiverLastName() string {
	if x != nil {
		return x.ReceiverLastName
	}
	return ""
}

func (x *Telegram) GetReceiverLanguageCode() string {
	if x != nil {
		return x.ReceiverLanguageCode
	}
	return ""
}

func (x *Telegram) GetReceiverIsPremium() bool {
	if x != nil {
		return x.ReceiverIsPremium
	}
	return false
}

func (x *Telegram) GetReceiverAllowsWriteToPm() bool {
	if x != nil {
		return x.ReceiverAllowsWriteToPm
	}
	return false
}

func (x *Telegram) GetReceiverPhotoUrl() string {
	if x != nil {
		return x.ReceiverPhotoUrl
	}
	return ""
}

func (x *Telegram) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Telegram) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Telegram) GetRawInitData() string {
	if x != nil {
		return x.RawInitData
	}
	return ""
}

func (x *Telegram) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Telegram) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\rcroki.auth.v1\x1a\x1bgoogle/protobuf/empty.proto\"u\n" +
	"\x18LoginWithTelegramRequest\x12\x1b\n" +
	"\tinit_data\x18\x01 \x01(\tR\binitData\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\"q\n" +
	"\x16LoginWithGoogleRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\"z\n" +
	"\x15RefreshSessionRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\"\xa8\x03\n" +
	"\rLoginResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.croki.auth.v1.UserR\x04user\x120\n" +
	"\aaccount\x18\x02 \x01(\v2\x16.croki.auth.v1.AccountR\aaccount\x120\n" +
	"\asession\x18\x03 \x01(\v2\x16.croki.auth.v1.SessionR\asession\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_at\x18\x05 \x01(\tR\x14accessTokenExpiresAt\x12#\n" +
	"\rrefresh_token\x18\x06 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_at\x18\a \x01(\tR\x15refreshTokenExpiresAt\x12\x1d\n" +
	"\n" +
	"token_type\x18\b \x01(\tR\ttokenType\x123\n" +
	"\btelegram\x18\t \x01(\v2\x17.croki.auth.v1.TelegramR\btelegram\"\xa1\x02\n" +
	"\x16RefreshSessionResponse\x120\n" +
	"\asession\x18\x01 \x01(\v2\x16.croki.auth.v1.SessionR\asession\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_at\x18\x03 \x01(\tR\x14accessTokenExpiresAt\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_at\x18\x05 \x01(\tR\x15refreshTokenExpiresAt\x12\x1d\n" +
	"\n" +
	"token_type\x18\x06 \x01(\tR\ttokenType\".\n" +
	"\x0fGetJWKSResponse\x12\x1b\n" +
	"\tjwks_json\x18\x01 \x01(\fR\bjwksJson\"Q\n" +
	"\x17GetSessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xaa\x01\n" +
	"\x18GetSessionStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x12\x1f\n" +
	"\vclient_type\x18\x05 \x01(\tR\n" +
	"clientType\"\xc0\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12*\n" +
	"\x11email_verified_at\x18\x04 \x01(\tR\x0femailVerifiedAt\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xb0\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xe3\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x9f\t\n" +
	"\bTelegram\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12(\n" +
	"\x10telegram_user_id\x18\x03 \x01(\x03R\x0etelegramUserId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12#\n" +
	"\rlanguage_code\x18\a \x01(\tR\flanguageCode\x12\x1d\n" +
	"\n" +
	"is_premium\x18\b \x01(\bR\tisPremium\x12+\n" +
	"\x12allows_write_to_pm\x18\t \x01(\bR\x0fallowsWriteToPm\x12\x1b\n" +
	"\tphoto_url\x18\n" +
	" \x01(\tR\bphotoUrl\x12\x1b\n" +
	"\tauth_date\x18\v \x01(\tR\bauthDate\x12\x19\n" +
	"\bquery_id\x18\f \x01(\tR\aqueryId\x12\x1f\n" +
	"\vstart_param\x18\r \x01(\tR\n" +
	"startParam\x12$\n" +
	"\x0ecan_send_after\x18\x0e \x01(\x05R\fcanSendAfter\x12\x17\n" +
	"\achat_id\x18\x0f \x01(\x03R\x06chatId\x12\x1b\n" +
	"\tchat_type\x18\x10 \x01(\tR\bchatType\x12\x1d\n" +
	"\n" +
	"chat_title\x18\x11 \x01(\tR\tchatTitle\x12#\n" +
	"\rchat_username\x18\x12 \x01(\tR\fchatUsername\x12$\n" +
	"\x0echat_photo_url\x18\x13 \x01(\tR\fchatPhotoUrl\x12#\n" +
	"\rchat_instance\x18\x14 \x01(\tR\fchatInstance\x12\x1f\n" +
	"\vreceiver_id\x18\x15 \x01(\x03R\n" +
	"receiverId\x12+\n" +
	"\x11receiver_username\x18\x16 \x01(\tR\x10receiverUsername\x12.\n" +
	"\x13receiver_first_name\x18\x17 \x01(\tR\x11receiverFirstName\x12,\n" +
	"\x12receiver_last_name\x18\x18 \x01(\tR\x10receiverLastName\x124\n" +
	"\x16receiver_language_code\x18\x19 \x01(\tR\x14receiverLanguageCode\x12.\n" +
	"\x13receiver_is_premium\x18\x1a \x01(\bR\x11receiverIsPremium\x12<\n" +
	"\x1breceiver_allows_write_to_pm\x18\x1b \x01(\bR\x17receiverAllowsWriteToPm\x12,\n" +
	"\x12receiver_photo_url\x18\x1c \x01(\tR\x10receiverPhotoUrl\x12\x12\n" +
	"\x04hash\x18\x1d \x01(\tR\x04hash\x12\x1c\n" +
	"\tsignature\x18\x1e \x01(\tR\tsignature\x12\"\n" +
	"\rraw_init_data\x18\x1f \x01(\tR\vrawInitData\x12\x1d\n" +
	"\n" +
	"created_at\x18  \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18! \x01(\tR\tupdatedAt2\xc8\x03\n" +
	"\vAuthService\x12Z\n" +
	"\x11LoginWithTelegram\x12'.croki.auth.v1.LoginWithTelegramRequest\x1a\x1c.croki.auth.v1.LoginResponse\x12V\n" +
	"\x0fLoginWithGoogle\x12%.croki.auth.v1.LoginWithGoogleRequest\x1a\x1c.croki.auth.v1.LoginResponse\x12]\n" +
	"\x0eRefreshSession\x12$.croki.auth.v1.RefreshSessionRequest\x1a%.croki.auth.v1.RefreshSessionResponse\x12A\n" +
	"\aGetJWKS\x12\x16.google.protobuf.Empty\x1a\x1e.croki.auth.v1.GetJWKSResponse\x12c\n" +
	"\x10GetSessionStatus\x12&.croki.auth.v1.GetSessionStatusRequest\x1a'.croki.auth.v1.GetSessionStatusResponseB3Z1github.com/xusk947/croki-proto/pkg/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auth_v1_auth_proto_goTypes = []any{
	(*LoginWithTelegramRequest)(nil), // 0: croki.auth.v1.LoginWithTelegramRequest
	(*LoginWithGoogleRequest)(nil),   // 1: croki.auth.v1.LoginWithGoogleRequest
	(*RefreshSessionRequest)(nil),    // 2: croki.auth.v1.RefreshSessionRequest
	(*LoginResponse)(nil),            // 3: croki.auth.v1.LoginResponse
	(*RefreshSessionResponse)(nil),   // 4: croki.auth.v1.RefreshSessionResponse
	(*GetJWKSResponse)(nil),          // 5: croki.auth.v1.GetJWKSResponse
	(*GetSessionStatusRequest)(nil),  // 6: croki.auth.v1.GetSessionStatusRequest
	(*GetSessionStatusResponse)(nil), // 7: croki.auth.v1.GetSessionStatusResponse
	(*User)(nil),                     // 8: croki.auth.v1.User
	(*Account)(nil),                  // 9: croki.auth.v1.Account
	(*Session)(nil),                  // 10: croki.auth.v1.Session
	(*Telegram)(nil),                 // 11: croki.auth.v1.Telegram
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	8,  // 0: croki.auth.v1.LoginResponse.user:type_name -> croki.auth.v1.User
	9,  // 1: croki.auth.v1.LoginResponse.account:type_name -> croki.auth.v1.Account
	10, // 2: croki.auth.v1.LoginResponse.session:type_name -> croki.auth.v1.Session
	11, // 3: croki.auth.v1.LoginResponse.telegram:type_name -> croki.auth.v1.Telegram
	10, // 4: croki.auth.v1.RefreshSessionResponse.session:type_name -> croki.auth.v1.Session
	0,  // 5: croki.auth.v1.AuthService.LoginWithTelegram:input_type -> croki.auth.v1.LoginWithTelegramRequest
	1,  // 6: croki.auth.v1.AuthService.LoginWithGoogle:input_type -> croki.auth.v1.LoginWithGoogleRequest
	2,  // 7: croki.auth.v1.AuthService.RefreshSession:input_type -> croki.auth.v1.RefreshSessionRequest
	12, // 8: croki.auth.v1.AuthService.GetJWKS:input_type -> google.protobuf.Empty
	6,  // 9: croki.auth.v1.AuthService.GetSessionStatus:input_type -> croki.auth.v1.GetSessionStatusRequest
	3,  // 10: croki.auth.v1.AuthService.LoginWithTelegram:output_type -> croki.auth.v1.LoginResponse
	3,  // 11: croki.auth.v1.AuthService.LoginWithGoogle:output_type -> croki.auth.v1.LoginResponse
	4,  // 12: croki.auth.v1.AuthService.RefreshSession:output_type -> croki.auth.v1.RefreshSessionResponse
	5,  // 13: croki.auth.v1.AuthService.GetJWKS:output_type -> croki.auth.v1.GetJWKSResponse
	7,  // 14: croki.auth.v1.AuthService.GetSessionStatus:output_type -> croki.auth.v1.GetSessionStatusResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
