// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: rag/v1/rag.proto

package ragv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_ExtractAndStoreMemory_FullMethodName = "/rag.v1.RagService/ExtractAndStoreMemory"
	RagService_RetrieveContext_FullMethodName       = "/rag.v1.RagService/RetrieveContext"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagServiceClient interface {
	ExtractAndStoreMemory(ctx context.Context, in *ExtractAndStoreMemoryRequest, opts ...grpc.CallOption) (*ExtractAndStoreMemoryResponse, error)
	RetrieveContext(ctx context.Context, in *RetrieveContextRequest, opts ...grpc.CallOption) (*RetrieveContextResponse, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) ExtractAndStoreMemory(ctx context.Context, in *ExtractAndStoreMemoryRequest, opts ...grpc.CallOption) (*ExtractAndStoreMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractAndStoreMemoryResponse)
	err := c.cc.Invoke(ctx, RagService_ExtractAndStoreMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) RetrieveContext(ctx context.Context, in *RetrieveContextRequest, opts ...grpc.CallOption) (*RetrieveContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveContextResponse)
	err := c.cc.Invoke(ctx, RagService_RetrieveContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
type RagServiceServer interface {
	ExtractAndStoreMemory(context.Context, *ExtractAndStoreMemoryRequest) (*ExtractAndStoreMemoryResponse, error)
	RetrieveContext(context.Context, *RetrieveContextRequest) (*RetrieveContextResponse, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) ExtractAndStoreMemory(context.Context, *ExtractAndStoreMemoryRequest) (*ExtractAndStoreMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractAndStoreMemory not implemented")
}
func (UnimplementedRagServiceServer) RetrieveContext(context.Context, *RetrieveContextRequest) (*RetrieveContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveContext not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call panics, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_ExtractAndStoreMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractAndStoreMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ExtractAndStoreMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ExtractAndStoreMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ExtractAndStoreMemory(ctx, req.(*ExtractAndStoreMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_RetrieveContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).RetrieveContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_RetrieveContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).RetrieveContext(ctx, req.(*RetrieveContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.v1.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractAndStoreMemory",
			Handler:    _RagService_ExtractAndStoreMemory_Handler,
		},
		{
			MethodName: "RetrieveContext",
			Handler:    _RagService_RetrieveContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag/v1/rag.proto",
}
